
if GetLocale() ~= "esES" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Fondo"
L["2. Border"] = "Borde"
L["3. Artwork"] = "Arte" -- Needs review
L["4. Overlay"] = "Superposición" -- Needs review
L["5. Highlight"] = "Resaltar" -- Needs review
L["Add Blend (additive)"] = "Agregar Mezcla (aditivo)" -- Needs review
L["Addon Buttons"] = "Botones del Addon" -- Needs review
L["A global profile already exists. You will be switched over to it and your UI will be reloaded, are you sure?"] = "Ya existe un perfil global. Éste se activará y tu UI será reiniciada. Estás seguro?" -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Permitir a SexyMap asumir control del arrastre de los botones junto al minimapa. Desactivelo si tienes otro mod que quieres usar para posicionar los botones del minimapa." -- Needs review
L["Alpha Key (1-bit alpha)"] = "Alfa Key (1-bit alpha)" -- Needs review
L["Always"] = "Siempre"
L["Armored Man"] = "Hombre Acorazado" -- Needs review
L["A static amount to rotate the texture by."] = "Una cantidad fija para girar la textura." -- Needs review
L["Auto Zoom-Out Delay"] = "Retraso del alejamiento automático" -- Needs review
L["Backdrop Color"] = "Color del Telón" -- Needs review
L["Backdrop Insets"] = "Añadidos al Telón" -- Needs review
L["Background Color"] = "Color del Fondo"
L["Background/edge"] = "Fondo/borde" -- Needs review
L["Background Texture"] = "Textura del Fondo"
L["Blend Mode"] = "Modo Mezcla" -- Needs review
L["Blend (normal)"] = "Mezclar (normal)" -- Needs review
L["Border Color"] = "Color del Borde"
L["Border Edge Size"] = "Tamaño del límite del borde" -- Needs review
L["Borders"] = "Bordes" -- Needs review
L["Border Texture"] = "Textura del Borde" -- Needs review
L["Boss Frames"] = "Frames de Boss" -- Needs review
L["Buttons"] = "Botones" -- Needs review
L["Calendar"] = "Calendario" -- Needs review
L["Capture Bars"] = "Capturar Barras" -- Needs review
L["Challenge Mode Button (When Available)"] = "Botón de Modo Desafío (cuando está disponible)" -- Needs review
L["Circle"] = "Círculo" -- Needs review
L["Clear the current borders and start fresh"] = "Limpiar los bordes actuales y comenzar de nuevo" -- Needs review
L["Clock"] = "Reloj" -- Needs review
L["Coordinates"] = "Coordenadas" -- Needs review
L["Copy a Profile"] = "Copiar un Perfil" -- Needs review
L["Create a new border"] = "Crear un nuevo borde" -- Needs review
L["Current Borders"] = "Bordes actuales" -- Needs review
L["Delete"] = "Eliminar" -- Needs review
L["Delete a Profile"] = "Borrar un Perfil" -- Needs review
L["Diamond"] = "Diamante" -- Needs review
L["Disable (opaque)"] = "Desactivar (opaco)" -- Needs review
L["Disable Rotation"] = "Desactivar la rotación" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Indicador de Dificultad de Mazmorra (Cuando esté disponible)" -- Needs review
L["Dynamic Buttons"] = "Botones dinámicos" -- Needs review
L["Enable"] = "Habilitar"
L["Enable Coordinates"] = "Habilitar Coordenadas"
L["Enable Hudmap"] = "Habilitar el Hudmap" -- Needs review
L["Font Size"] = "Tamaño de Fuente"
L["Height"] = "Alto" -- Needs review
L["Hexagon"] = "Hexágono"
L["Horizontal Position"] = "Posición Horizontal"
L["HUD Color"] = "Color del HUD" -- Needs review
L["Map Button"] = "Botón del Mapa"
L["Name"] = "Nombre"
L["Never"] = "Nunca"
L["Octagon"] = "Octágono" -- Needs review
L["Really delete this profile?"] = "¿De verdad quieres borrar este perfil?" -- Needs review
L["Right Click Configure"] = "Configurar Click Derecho" -- Needs review
L["Right clicking the map will open the SexyMap options"] = "Haciendo click derecho en el mapa se abrirán las opciones de SexyMap" -- Needs review
L["Rotation Speed (seconds)"] = "Velocidad de Rotación (segundos)" -- Needs review
L["Route 66"] = "Ruta 66" -- Needs review
L["Save current settings as preset..."] = "Guardar configuración actual como predeterminada..." -- Needs review
L["Scale"] = "Escala" -- Needs review
L["Spice up your minimap with some sexy options."] = "Condimenta tu minimapa con unas cuantas opciones sexys." -- Needs review
L["Text Color"] = "Color del Texto" -- Needs review
L["Texture"] = "Textura" -- Needs review
L["Texture Options"] = "Opciones de Textura" -- Needs review
L["The time it takes (in seconds) to complete one rotation. A setting of 0 turns off rotation."] = "El tiempo que tardará (en segundos) en dar una vuelta completa. Marcar 0 deshabilitará la rotación" -- Needs review
L["Use Global Profile"] = "Usar el perfil global" -- Needs review
L["Visibility"] = "Visibilidad" -- Needs review
L["Width"] = "Ancho" -- Needs review
L["Zoom In Button"] = "Botón de Acercar Zoom" -- Needs review
L["Zoom Out Button"] = "Botón de Alejar Zoom" -- Needs review


